### ISSUE TITLE
** Feature Request **

### ISSUE THREAD

**Issue by gurrilamail** [chakrakan/fit4less-autobooker#12]
Hello,
Hope you are doing well! 

I want to start off by saying thank you for making this! Its been amazing to have my workouts auto booked with Cron Jobs.

I do have a feature request that I was wondering if you could implement. I was wondering if you could implement a date variable along side the days ahead variable?

So the script should only require one of those variables. Either days ahead or Date

This new variable would be useful as on those odd times that you do not get a booking at your desired time slot you could then run a cron job every 5 minutes with the Date variable and it will keep checking for set time slots on set date Even if it is a new date.

Thank you!

**Comment by gurrilamail** [comment]
DISREGARD

I Should have read the code

**Comment by chakrakan** [comment]
no worries, glad it's helped you thus far and thanks for suggesting a feature.

I hope the script keeps working, but if it doesn't do let me know because I've cancelled my membership temporarily due to covid and as such, I'm unable to maintain this repo as I don't have access to the platform anymore. 

I'll add a note to the readme, and if someone wants to maintain this for the time being, feel free to make pull requests.

Cheers!
